[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
basic = "9z8uxjk3xUrsPdhemP4Qzq5dzqhHjZ2x9kP56dm28hcv"

[programs.devnet]
dead_mans_switch = "H6ETDMJrcvhaJnYBEbTkSLjFQbrKTucQvMBPCKh8qpG8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/media/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8910
