[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dead_mans_switch = "GxpMKCELhKsaEAn6dhHwSw2JrNF5DXDyyfYo3zWibdvQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
