[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dead_mans_switch = "GxpMKCELhKsaEAn6dhHwSw2JrNF5DXDyyfYo3zWibdvQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8900"
wallet = "~/.config/solana/id.json"
faucet_port = 9901

[scripts]
test = "npm run test"
